<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> PersonalMail </title>
    <!-- Define site icon in browser -->
    <link rel="shortcut icon" href="./img/lollipop-icon-email-primary.png" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Font Awesome Link -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Internal CSS -->
    <link rel="stylesheet" href="./css/style_default.css">
</head>
<body class="bg-light">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            <img src="./img/lollipop-icon-email-primary.png" width="30" height="30" class="d-inline-block align-top" alt="SendMail">
            PersonalMail
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#"> Home <span class="sr-only">(Página atual)</span></a>
                </li>
				<li class="nav-item">
                    <a class="nav-link" href="/new"> Criar e-mail </a>
                </li>
            </ul>
        </div>
    </nav>
	<br>
    <div class="container-fluid">

		<div class="jumbotron">
			<h1 class="display-4">App PersonalMail</h1>
			<p class="lead">
				Esta aplicação foi desenvolvida apenas com o objetivo de aprendizado sobre desenvolvimento em plataforma web e bibliotecas das linguagens PHP e JavaScript.
			</p>
			<hr class="my-4">
			<p>
				Os dados fornecidos e utilizados nesta aplicação não são armazenados em lugar algum. <strong>Apenas estatísticas de uso são consideradas.</strong>
			</p>
			<!-- <a class="btn btn-primary btn-lg" href="#" role="button">Leia mais</a> -->
			<p>
				<a class="btn btn-primary btn-lg" data-toggle="collapse" href="#privacyPolicy" role="button" aria-expanded="false" aria-controls="privacyPolicy">
					Tratamento dos dados
				</a>
				<a href="https://github.com/felipewesley" class="btn btn-dark btn-lg" title="Ver projeto GitHub" target="_blank">
					<i class="fa fa-github"></i>
					Projeto no GitHub
				</a>
			</p>

			<div class="collapse" id="privacyPolicy">
				<div class="card card-body">
					<p>
					Os dados utilizados aqui não são armazenados em cache ou cookies do navegador, banco de dados ou em qualquer outro formato de armazenamento.
					</p>
					<p>
					Todos os dados utilizados nesta aplicação são processados em tempo de execução e descartados logo em seguida.
					</p>
					<p>
					Apenas suas estatísticas de uso são armazenadas para a geração dos gráficos da seção <a href="#" class="badge badge-dark"> Estatísticas </a>.
					</p>
					<div class="alert alert-dark" role="alert">
						Se ainda assim não se sentir seguro para utilizar esta aplicação, crie um pull-request no repositório deste projeto, sugerindo melhorias no processo de tratamento de dados.
					</div>
				</div>
			</div>
		</div>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Script interno da aplicação -->

</body>
</html>
