<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Personal Mail </title>
    <!-- Define site icon in browser -->
    <link rel="shortcut icon" href="./img/lollipop-icon-email-primary.png" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Font Awesome Link -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- CSS WebTextEditor -->
    <link rel="stylesheet" type="text/css" href="./lib/TextEditor/css/editor.css">
    <!-- Internal CSS -->
	<link rel="stylesheet" href="./css/style_default.css">
	<!-- Script jQuery -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</head>
<body class="bg-light">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">
            <img src="./img/lollipop-icon-email-primary.png" width="30" height="30" class="d-inline-block align-top" alt="SendMail">
            PersonalMail
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/home"> Home <span class="sr-only">(Página atual)</span></a>
                </li>
				<li class="nav-item active">
                    <a class="nav-link" href="#"> Criar e-mail </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#"> Sobre </a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="jumbotron jumbotron-fluid" id="jb-novo-email">
        <div class="container">
            <h1 class="display-4"> Novo e-mail </h1>
        </div>
    </div>

    <div class="container-fluid">

        <form action="/confirm" method="post" class="needs-validation" id="frm-main" novalidate>

            <div class="form-row">
                <div class="form-group col-md-4">
                    <div class="form-row">
                        <label for="inputEmail"> Destinatário </label>
                        <input type="email" class="form-control input-v" name="destino" id="inputEmail" placeholder="destinatario@email.com" required>
                    </div>
                    <div class="form-row">
                        <label for="inputAssunto"> Assunto </label>
                        <input type="text" class="form-control input-v" name="assunto" id="inputAssunto" placeholder="Assunto">
                    </div>
                </div>
                <div class="form-group col-md-1"></div>
                <div class="form-group col-md-6">
                    <label for="txt-content"> Mensagem </label>
                    <textarea id="txt-content" name="txt-content"></textarea>
                </div>
            </div>

            <button type="button" class="btn btn-lg btn-primary" data-toggle="modal" data-target="#userAccountConfirm" id="btn-confirm-user">
                <i class="fa fa-send-o"></i>
                <span style="padding-left: 10px;"> Enviar </span>
            </button>

            <br><br>

            <!-- Modal para insereção de usuário e senha do utilizador -->
            <div class="modal fade" id="userAccountConfirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog modal-dialog-centered" role="document">
					<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Confirmar usuário</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
						<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<p>
							<small>
								Insira o e-mail e senha da conta de usuário que queira utilizar como remetente
							</small>
						</p>

						<div class="form-group">
							<label for="name_user" class="col-form-label">Insira seu nome</label>
							<input type="text" class="form-control" id="name_user" name="user_idname" placeholder="Seu nome">
						</div>
						<div class="form-group">
							<label for="email_user" class="col-form-label">Usuário</label>
							<input type="email" class="form-control" id="email_user" name="user_username" placeholder="example@mail.com" required>
						</div>
						<div class="form-group">
							<label for="password_user" class="col-form-label">Senha</label>
							<input type="password" class="form-control" name="user_password" id="password_user" placeholder="password" required>
						</div>

					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
						<button type="submit" class="btn btn-primary" id="btn-enviar">
							Enviar
						</button>
					</div>
					</div>
				</div>
            </div>

        </form>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<!-- Script Bootstrap para bloquear submit caso haja campos inválidos -->
	<script>
	// Exemplo de JavaScript inicial para desativar envios de formulário, se houver campos inválidos.
	(function() {
	'use strict';
	window.addEventListener('load', function() {
		// Pega todos os formulários que nós queremos aplicar estilos de validação Bootstrap personalizados.
		var forms = document.getElementsByClassName('needs-validation');
		// Faz um loop neles e evita o envio
		var validation = Array.prototype.filter.call(forms, function(form) {
		form.addEventListener('submit', function(event) {
			if (form.checkValidity() === false) {
				event.preventDefault();
				event.stopPropagation();
			}
			form.classList.add('was-validated');
		}, false);
		});
	}, false);
	})();
	</script>
    <!-- JavaScript e jQuery do editor de texto -->
    <script src="./lib/TextEditor/js/jquery-1.12.0.js"></script>
    <script src="./lib/TextEditor/js/editor.js"></script>
    <script type="text/javascript">
		$(document).ready(function() {
			$('#txt-content').Editor();

            // $('#txt-content').Editor('setText', ['<p>Sua mensagem vai aqui</p>']);

			$('#btn-enviar').click(e => {
				e.preventDefault();
                $('#txt-content').text($('#txt-content').Editor('getText'));

				if($('input#inputEmail').val() == ''){
					$('input#inputEmail').addClass('is-invalid')
				}else{
					$('input#inputEmail').removeClass('is-invalid')
				}
				if($('input#email_user').val() == ''){
					$('input#email_user').addClass('is-invalid')
				}else{
					$('input#email_user').removeClass('is-invalid')
				}
				if($('input#password_user').val() == ''){
					$('input#password_user').addClass('is-invalid')
				}else{
					$('input#password_user').removeClass('is-invalid')
				}

				if($('.is-invalid').length === 0){
					$('#frm-main').submit();
				}
                /* Efetuar evento de envio após validações */
			});

			$('#btn-confirm-user').click(e => {

				// e.preventDefault();

				if($('input#inputEmail').val() == ''){
					$('input#inputEmail').addClass('is-invalid')
				}else{
					$('input#inputEmail').removeClass('is-invalid')
				}

			});
		});
	</script>

</body>
</html>
